version: '3.7'
services:
 proyecto-micro01:
  container_name: 'proyecto-micro01'
  image: danivallejo92/proyect:v1
  ports:
   - "5001:4001"
  networks:
   - proyecto
  environment:
   CONTAINER_HOST: proyecto-micro01
 proyecto-micro02:
  container_name: proyecto-micro02
  image: danivallejo92/proyect:v1
  ports:
   - "5002:4001"
  networks:
   - proyecto
  environment:
   CONTAINER_HOST: proyecto-micro02    
 load-balancer:
  container_name: 'load-balancer'
  image: load-balancer:v1
  build:
   context: ./load-balancer
  ports:
   - "8082:80"
  networks:
   - proyecto
  depends_on:
   - proyecto-micro01
   - proyecto-micro02
  restart: always
networks:
 proyecto: